### ISSUE TITLE
1.16.1 crash

### ISSUE THREAD

**Issue by machinesmith42** [LambdAurora/LambdaControls#15]
MultiMC version: 0.6.11-1430

Minecraft folder is:
D:/Downloads/mmc-stable-win32(2)/MultiMC/instances/1.16.1/.minecraft

Java path is:
C:/Program Files/ojdkbuild/java-14-openjdk-jre-14.0.1-1/bin/javaw.exe

Java is version 14.0.1, using 64-bit architecture.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  D:/Downloads/mmc-stable-win32(2)/MultiMC/instances/1.16.1/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/mojang/datafixerupper/3.0.25/datafixerupper-3.0.25.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/fabricmc/intermediary/1.16.1/intermediary-1.16.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/fabricmc/tiny-remapper/0.2.2.64/tiny-remapper-0.2.2.64.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/ow2/asm/asm/8.0/asm-8.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/ow2/asm/asm-analysis/8.0/asm-analysis-8.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/ow2/asm/asm-commons/8.0/asm-commons-8.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/ow2/asm/asm-tree/8.0/asm-tree-8.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/ow2/asm/asm-util/8.0/asm-util-8.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/fabricmc/fabric-loader/0.8.8+build.202/fabric-loader-0.8.8+build.202.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/mojang/minecraft/1.16.1/minecraft-1.16.1-client.jar

Native libraries:
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] appleskin-mc1.16-fabric-1.0.11
  [✔️] carpet-extra-1.16-1.4.0
  [✔️] chat-up-1.0.0-1.16
  [✔️] cleardespawn-1.16-fabric0.13.1-1.1.0
  [✔️] durabilityviewer-1.16-fabric0.13.1-1.7.1(1)
  [✔️] fabric-api-0.13.1+build.370-1.16
  [✔️] fabric-carpet-1.16-1.4.0+v200623
  [✔️] g4mespeed-1.0.6-mc1.16.1-release(1)
  [✔️] Hwyla-fabric-1.16-1.9.22-74
  [❌] immersive-portals-0.13(forMc1.16.1withFabric).jar (disabled)
  [✔️] itemscroller-fabric-1.16.0-0.15.0-dev.20200624.214738
  [✔️] lambdacontrols-fabric-1.3.2+1.16.1
  [❌] light-overlay-5.4.0.jar (disabled)
  [✔️] lithium-fabric-mc1.16.1
  [❌] logical_zoom-0.0.2.jar (disabled)
  [✔️] malilib-fabric-1.16.0-0.10.0-dev.21+beta.2
  [✔️] minihud-fabric-1.16.0-0.19.0-dev.20200625.014835
  [✔️] modmenu-1.12.2+build.17
  [✔️] mousewheelie-1.4.16+mc1.16-rc1
  [✔️] okzoomer-4.0.0-alpha.3.1.16.pre5
  [✔️] phosphor-fabric-mc1.16.1
  [✔️] RoughlyEnoughItems-4.5.5
  [✔️] shulkerboxtooltip-2.1.0+1.16.1
  [✔️] sodium-fabric-mc1.16.1
  [✔️] stackablepotionsandbuckets-1.0

Params:
  --username  --version MultiMC5 --gameDir D:/Downloads/mmc-stable-win32(2)/MultiMC/instances/1.16.1/.minecraft --assetsDir D:/Downloads/mmc-stable-win32(2)/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:+UnlockExperimentalVMOptions, -XX:+UseZGC, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms409m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 7352

Using onesix launcher.

[18:07:34] [main/INFO]: Loading for game Minecraft 1.16.1
[18:07:36] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-keybindings-v0: used 0.2.0+3fa9f7c57c, also found 0.2.0+3fa9f7c5b0
 - Conflicting versions found for fabric-api-base: used 0.1.3+12a8474cb0, also found 0.1.3+12a8474c7c, 0.1.3+12a8474cb2
 - Conflicting versions found for fabric-tool-attribute-api-v1: used 1.1.4+5794386e7c, also found 1.1.4+5794386eb0
 - Conflicting versions found for fabric-events-interaction-v0: used 0.3.3+7066030f7c, also found 0.3.3+7066030fb0
 - Conflicting versions found for fabric-key-binding-api-v1: used 1.0.0+e16a9774b0, also found 1.0.0+e16a97747c
 - Conflicting versions found for fabric-resource-loader-v0: used 0.2.5+059ea8667c, also found 0.2.5+059ea866b0
 - Conflicting versions found for fabric-tag-extensions-v0: used 0.2.5+5a6e8f4c7c, also found 0.2.5+5a6e8f4cb0
 - Conflicting versions found for fabric-events-lifecycle-v0: used 0.1.3+0d474ec47c, also found 0.1.3+0d474ec4b0, 0.1.3+0d474ec4b2
[18:07:36] [main/WARN]: Mod `tweed` (3.0.0-beta.9) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[18:07:37] [main/INFO]: [FabricLoader] Loading 72 mods: cleardespawn@1.16-fabric0.13.1-1.1.0, fabric-renderer-api-v1@0.2.13+eae12eb87c, fabric-keybindings-v0@0.2.0+3fa9f7c57c, gbfabrictools@1.2.2+1.16, fabricloader@0.8.8+build.202, org_aperlambda_lambdajcommon@1.8.0, lithium@0.5.0-rc1-SNAPSHOT, fabric-containers-v0@0.1.8+045df74f7c, fabric-dimensions-v1@1.0.0+a71b30537c, fabric-object-builder-api-v1@1.5.5+e00ecb5f7c, fabric-api-base@0.1.3+12a8474cb0, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d7c, fiber@0.23.0-1, fabric-textures-v0@1.0.4+eae12eb87c, com_electronwill_night-config_core@3.5.3, fabric-rendering-fluids-v1@0.1.7+12a8474c7c, waila@1.9.22, fabric-blockrenderlayer-v1@1.1.4+c6a8ea897c, sodium@0.1.0-SNAPSHOT, fabric-renderer-registries-v1@2.0.1+5a0f9a607c, minihud@0.19.0-dev.20200625.014835, carpet-extra@1.4.0, fabric-loot-tables-v1@0.1.10+059ea8667c, fabric@0.13.1+build.370-1.16, carpet@1.4.0, fabric-particles-v1@0.2.1+0a6f2a707c, fabric-networking-v0@0.1.10+e00ecb5f7c, chat-up@1.0, minecraft@1.16.1, okzoomer@4.0.0-alpha.3.1.16.pre5, fabric-screen-handler-api-v1@1.0.1+f362c86e7c, fabric-networking-blockentity-v0@0.2.5+b50ffc7b7c, lambdacontrols@1.3.2+1.16.1, modmenu@1.12.2+build.17, fabric-command-api-v1@1.0.8+5ce533987c, cloth-basic-math@0.5.1, phosphor@0.6.0-SNAPSHOT, amecsapi@1.0.2+1.16-rc1, stackablepotionsandbuckets@1.0, fabric-tool-attribute-api-v1@1.1.4+5794386e7c, g4mespeed@1.0.6-mc1.16.1, fabric-renderer-indigo@0.3.1+059ea8667c, com_electronwill_night-config_toml@3.5.3, cloth-client-events-v0@1.0.4, fabric-biomes-v1@0.2.7+059ea8667c, roughlyenoughitems@4.5.5, fabric-events-interaction-v0@0.3.3+7066030f7c, fabric-crash-report-info-v1@0.1.2+b7f9825d7c, fabric-rendering-v0@1.1.0+534104907c, mousewheelie@1.4.16+mc1.16-rc1, fabric-key-binding-api-v1@1.0.0+e16a9774b0, fabric-rendering-v1@1.1.2+346247d77c, cloth-config2@4.5.6, spruceui@1.5.2, autoconfig1u@3.2.0-unstable, fabric-resource-loader-v0@0.2.5+059ea8667c, malilib@0.10.0-dev.21+beta.2, fabric-content-registries-v0@0.1.9+059ea8667c, fabric-tag-extensions-v0@0.2.5+5a6e8f4c7c, appleskin@1.0.11, fabric-commands-v0@0.2.0+52d308367c, fabric-registry-sync-v0@0.3.8+7dba2d6c7c, durabilityviewer@1.16-fabric0.13.1-1.7.1, itemscroller@0.15.0-dev.20200624.214738, fabric-mining-levels-v0@0.1.2+b764ce997c, fabric-events-lifecycle-v0@0.1.3+0d474ec47c, fabric-item-groups-v0@0.2.0+438f96367c, fabric-models-v0@0.1.0+dfdb52d67c, shulkerboxtooltip@2.1.0+1.16.1, fabric-object-builders-v0@0.6.0+da175ad67c, tweed@3.0.0-beta.9, org_jetbrains_annotations@17.0.0
[18:07:37] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[18:07:53] [main/INFO]: Loaded configuration file for Sodium (32 options available, 0 user overrides)
[18:07:53] [main/INFO]: Sodium has been successfully discovered and initialized -- your game is now faster!
[18:07:53] [main/INFO]: Loaded configuration file for Lithium (40 options available, 0 user overrides)
[18:07:53] [main/INFO]: Lithium has been successfully discovered and initialized -- your game is now faster!
[18:07:53] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-v0.mixins.json:MixinEntityTracker and should be specified in value
[18:07:55] [main/WARN]: @Mixin target net/minecraft/class_5120$class_5121 is public in fabric-tag-extensions-v0.mixins.json:MixinTagImpl and should be specified in value
[18:07:55] [main/WARN]: @Mixin target net.minecraft.class_5394 is public in fabric-tag-extensions-v0.mixins.json:MixinTagImpl and should be specified in value
[18:13:15] [main/INFO]: Narrator library for x64 successfully loaded
[18:13:46] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[18:13:48] [main/INFO]: Setting user: MachineSmith42
[18:14:36] [main/INFO]: Discovered plugin waila:core provided by waila at mcp.mobius.waila.addons.core.PluginCore
[18:14:37] [main/INFO]: Discovered plugin waila:vanilla provided by waila at mcp.mobius.waila.addons.minecraft.PluginMinecraft
[18:14:37] [main/INFO]: Registering plugin at mcp.mobius.waila.addons.core.PluginCore
[18:14:38] [main/INFO]: Registering plugin at mcp.mobius.waila.addons.minecraft.PluginMinecraft
[18:14:42] [main/INFO]: [LambdaControls] Initializing LambdaControls...
[18:14:42] [main/INFO]: Carpet mod detected!
[18:14:50] [main/INFO]: G4mespeed 1.0.6 initialized!
[18:15:52] [main/INFO]: [Ok Zoomer Next] °w° what's this
[18:15:58] [main/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[18:16:01] [main/INFO]: Config loaded.
[18:16:06] [main/INFO]: Reloaded configs for mousewheelie (universal/highest)
[18:16:06] [main/ERROR]: Config files should contain an hjson object!
[18:16:06] [main/ERROR]: Failed to read config file tweed.hjson
[18:16:06] [main/ERROR]: Config files should contain an hjson object!
[18:16:06] [main/ERROR]: Failed to read config file tweed.hjson
[18:16:06] [main/INFO]: Reloaded configs for tweed (universal/highest)
---- Minecraft Crash Report ----
// You're mean.

Time: 6/29/20, 6:16 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'lambdacontrols'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:425)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
	Suppressed: java.lang.reflect.UndeclaredThrowableException
		at com.sun.proxy.$Proxy40.onInitializeClient(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 19 more
	Caused by: java.lang.reflect.InvocationTargetException
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.base/java.lang.reflect.Method.invoke(Unknown Source)
		at net.fabricmc.loader.util.DefaultLanguageAdapter$1.invoke(DefaultLanguageAdapter.java:122)
		... 21 more
	Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/event/lifecycle/v1/ClientTickEvents
		at me.lambdaurora.spruceui.hud.HudManager.initialize(HudManager.java:42)
		... 26 more
	Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
		at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
		... 27 more
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/event/lifecycle/v1/ClientTickEvents
	at me.lambdaurora.lambdacontrols.client.LambdaControlsClient.onInitializeClient(LambdaControlsClient.java:82)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 19 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:425)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 14.0.1, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3248488448 bytes (3098 MB) / 4257218560 bytes (4060 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms409m -Xmx4096m
	Fabric Mods: 
		amecsapi: Amecs API 1.0.2+1.16-rc1
		appleskin: AppleSkin 1.0.11
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		carpet: Carpet Mod in Fabric 1.4.0
		carpet-extra: Carpet Extra 1.4.0
		chat-up: Chat Up! 1.0
		cleardespawn: Clear Despawn 1.16-fabric0.13.1-1.1.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.5.6
		com_electronwill_night-config_core: core 3.5.3
		com_electronwill_night-config_toml: toml 3.5.3
		durabilityviewer: Giselbaers Durability Viewer 1.16-fabric0.13.1-1.7.1
		fabric: Fabric API 0.13.1+build.370-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cb0
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea8667c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea897c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533987c
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308367c
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f7c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8667c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d7c
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b30537c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f7c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.3+0d474ec47c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96367c
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a9774b0
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c57c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea8667c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce997c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d67c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b7c
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f7c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f7c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad67c
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a707c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c7c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb87c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.1+059ea8667c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a607c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d7c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.7+12a8474c7c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104907c
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d77c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.5+059ea8667c
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e7c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.5+5a6e8f4c7c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb87c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e7c
		fabricloader: Fabric Loader 0.8.8+build.202
		fiber: fiber 0.23.0-1
		g4mespeed: G4mespeed 1.0.6-mc1.16.1
		gbfabrictools: GBfabrictools 1.2.2+1.16
		itemscroller: Item Scroller 0.15.0-dev.20200624.214738
		lambdacontrols: LambdaControls 1.3.2+1.16.1
		lithium: Lithium 0.5.0-rc1-SNAPSHOT
		malilib: MaLiLib 0.10.0-dev.21+beta.2
		minecraft: Minecraft 1.16.1
		minihud: MiniHUD 0.19.0-dev.20200625.014835
		modmenu: Mod Menu 1.12.2+build.17
		mousewheelie: Mouse Wheelie 1.4.16+mc1.16-rc1
		okzoomer: Ok Zoomer 4.0.0-alpha.3.1.16.pre5
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.0
		org_jetbrains_annotations: annotations 17.0.0
		phosphor: Phosphor 0.6.0-SNAPSHOT
		roughlyenoughitems: Roughly Enough Items 4.5.5
		shulkerboxtooltip: Shulker Box Tootip 2.1.0+1.16.1
		sodium: Sodium 0.1.0-SNAPSHOT
		spruceui: SpruceUI 1.5.2
		stackablepotionsandbuckets: Example Mod 1.0
		tweed: Tweed API 3.0.0-beta.9
		waila: Hwyla 1.9.22
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# D:\Downloads\mmc-stable-win32(2)\MultiMC\instances\1.16.1\.minecraft\crash-reports\crash-2020-06-29_18.16.07-client.txt
Process exited with code -1.
Clipboard copy at: 29 Jun 2020 18:17:00 -0500

**Comment by LambdAurora** [comment]
The crash seems to be the same as #14 :

> Hello, I believe you have an older version of Fabric API, try updating it and it should work!
>
> https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/2988824
>
> Let me know if this work, if not then it's very weird.

**Comment by machinesmith42** [comment]
readded the fabric api and still crashing

**Comment by LambdAurora** [comment]
Do you have the same crash? or is it different?
And what is the version of Fabric API you installed?

**Comment by machinesmith42** [comment]
same crash
fabric api version 14

**Comment by LambdAurora** [comment]
Can you please post the latest crash report to be sure?

**Comment by machinesmith42** [comment]
sure one moment

**Comment by machinesmith42** [comment]
nevermind redowloaded v14 and is working now
