### ISSUE TITLE
Issues with Fabric version

### ISSUE THREAD

**Issue by bobstar3233** [LambdAurora/LambdaControls#30]
Flat crashes.
Using fabric loader 0.9.3 build 208-1.16.2

Error log:
21:29:53.757
launcher
main
Starting!
21:29:53.988
launcher
main
Using default game log configuration client-1.12.xml (outputs XML)
21:29:57.521
FabricLoader
main
Loading for game Minecraft 1.16.2
21:29:58.494
Fabric|Loader
main
A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: lambdacontrols requires {fabric @ [>=0.4.0]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:169)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:604)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:202)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:167)
	... 5 more
21:29:58.550
launcher
main

21:29:58.550
monitor
Process Monitor
Process crashed with exit code 1

**Comment by bobstar3233** [comment]
Fixed with fabric api
